#!/usr/bin/env bun
import * as acp from "@agentclientprotocol/sdk";

import { CODEX_ACP_NPX_ARGS, CODEX_ACP_NPX_COMMAND } from "../lib/acp";
import { readableToWebStream, writableToWebStream } from "./stdio-web-stream";

function buildTemplateJson(promptText: string): string {
  const briefMatch = promptText.match(/\[Brief\]\n([\s\S]+)$/u);
  const brief = briefMatch?.[1]?.trim() || "generated collaboration pod";
  const incident = /incident|告警|故障|debug|排障/i.test(brief);

  return JSON.stringify(
    {
      name: incident ? "Mock Incident Pod" : "Mock Collaboration Pod",
      description: `Generated by mock ACP from brief: ${brief}`,
      accentTone: incident ? "blueprint" : "postit",
      members: [
        {
          id: "entry",
          name: incident ? "Dispatch Gull" : "Lead Koi",
          handle: "lead",
          summary: "入口成员，接用户消息并协调其他成员。",
          prompt: `围绕 brief 组织协作：${brief}`,
          accentTone: incident ? "blueprint" : "postit",
          provider: {
            kind: "codex-acp",
            label: "Codex ACP",
            command: CODEX_ACP_NPX_COMMAND,
            args: CODEX_ACP_NPX_ARGS,
            env: {},
            capabilities: ["prompt", "cancel", "loadSession"],
          },
          isEntryMember: true,
          observeAllRoomMessages: true,
          acceptsDirectMessages: true,
          skills: [
            {
              id: "send-group",
              name: "发送群消息",
              description: "向群组广播状态。",
              command: "./bin/oa-room-send --scope group",
            },
          ],
        },
        {
          id: "builder",
          name: incident ? "Probe Fox" : "Forge Crab",
          handle: incident ? "investigator" : "builder",
          summary: incident ? "负责排障证据链。" : "负责实现和工程落地。",
          prompt: incident ? "你负责排障证据链和复现。" : "你负责实现和测试。",
          accentTone: "paper",
          provider: {
            kind: "generic-acp",
            label: incident ? "Investigator ACP" : "Builder ACP",
            command: incident ? "investigator-acp" : "claude-code",
            args: ["--stdio"],
            env: {},
            capabilities: ["prompt", "cancel"],
          },
          observeAllRoomMessages: false,
          acceptsDirectMessages: true,
          skills: [
            {
              id: "inspect-room",
              name: "查看房间状态",
              description: "读取当前房间消息。",
              command: "./bin/oa-room-state --room \"$ROOM\"",
            },
          ],
        },
      ],
    },
    null,
    2,
  );
}

class MockAgent implements acp.Agent {
  private readonly connection: acp.AgentSideConnection;
  private readonly sessions = new Map<string, AbortController>();

  constructor(connection: acp.AgentSideConnection) {
    this.connection = connection;
  }

  initialize(): Promise<acp.InitializeResponse> {
    return Promise.resolve({
      protocolVersion: acp.PROTOCOL_VERSION,
      agentCapabilities: {
        loadSession: false,
      },
      agentInfo: {
        name: "OpenAquarium Mock ACP",
        version: "0.1.0",
      },
    });
  }

  newSession(): Promise<acp.NewSessionResponse> {
    const sessionId = crypto.randomUUID();
    this.sessions.set(sessionId, new AbortController());
    return Promise.resolve({ sessionId });
  }

  authenticate(): Promise<acp.AuthenticateResponse> {
    return Promise.resolve({});
  }

  async prompt(params: acp.PromptRequest): Promise<acp.PromptResponse> {
    const controller = this.sessions.get(params.sessionId) ?? new AbortController();
    this.sessions.set(params.sessionId, controller);
    const promptText = params.prompt
      .filter((content): content is Extract<(typeof params.prompt)[number], { type: "text" }> => content.type === "text")
      .map((content) => content.text)
      .join("\n");

    const chunks = promptText.includes("[OA_TEMPLATE_GENERATION]")
      ? [buildTemplateJson(promptText)]
      : [
          "收到任务。我会先整理当前房间上下文。",
          "如果需要协调其他成员，我会在最终消息里明确 @handle。",
        ];

    for (const chunk of chunks) {
      if (controller.signal.aborted) {
        return { stopReason: "cancelled" };
      }

      await this.connection.sessionUpdate({
        sessionId: params.sessionId,
        update: {
          sessionUpdate: "agent_message_chunk",
          content: {
            type: "text",
            text: chunk,
          },
        },
      });
      await new Promise((resolve) => setTimeout(resolve, 25));
    }

    return { stopReason: "end_turn" };
  }

  cancel(params: acp.CancelNotification): Promise<void> {
    this.sessions.get(params.sessionId)?.abort();
    this.sessions.set(params.sessionId, new AbortController());
    return Promise.resolve();
  }
}

const stream = acp.ndJsonStream(writableToWebStream(process.stdout), readableToWebStream(process.stdin));
new acp.AgentSideConnection((connection) => new MockAgent(connection), stream);
